os:
  - linux

language: php

php:
  - '7.1'

before_script:
  - composer self-update
  - composer install --no-interaction
  - cp .env.travis .env
  - php artisan migrate:fresh --seed

script:
  - vendor/bin/phpunit --coverage-text