os:
  - linux

language: php

php:
  - '7.1'

services:
  - mysql

before_install:
  - mysql -e 'CREATE DATABASE homestead_test;'

before_script:
  - composer self-update
  - composer install --no-interaction
  - cp .env.travis .env
  - php artisan migrate:fresh --seed
  - php artisan jwt:secret

script:
  - vendor/bin/phpunit --coverage-text