<?php

namespace Tests\Feature;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;
use Tests\Utils\GenerateToken;


class NoteTest extends TestCase
{
    use RefreshDatabase,GenerateToken;


    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    /**
     * Get all notes.
     *
     * @return void
     */
    public function testGetNotes()
    {

        $response = $this->withoutMiddleware()
            ->json(
                'GET',
                'api/notes',
                [],
                ['Authorization' => 'Bearer ' . $this->getToken()]
            )
            ->assertStatus(200);

        $response->assertStatus(200);
    }

    /**
     * Try get notes without token.
     *
     * @return void
     */
    public function testGetNotesUnhappyUnauthenticated()
    {

        $response = $this->withoutMiddleware()
            ->json(
                'GET',
                'api/notes',
                [],
                []
            )
            ->assertStatus(401);

        $response->assertStatus(401);
    }
}