<?php

namespace Tests\Feature;

use Tests\TestCase;
use Tests\Utils\GenerateToken;


class TagTest extends TestCase
{
    use GenerateToken;


    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    /**
     * Get all notes.
     *
     * @return void
     */
    public function testGetTags()
    {
        $response = $this->withoutMiddleware()
            ->json(
                'POST',
                'api/tags',
                ['id' => 1, 'name' => 'newName1'],
                ['Authorization' => 'Bearer ' . $this->getToken()]
            )
            ->assertStatus(200)
            ->decodeResponseJson('success');

        $this->assertEquals(true, $response, 'Update should be successful');
    }


}